title = "Luc1f3r's Blog"

baseURL = 'https://blog.luc1f3r.top/'

theme = 'FixIt'

defaultContentLanguage = 'zh-cn'
languageCode = 'zh-CN'
languageName = "简体中文"
hasCJKLanguage = true

enableRobotsTXT = true
enableEmoji = true


# 继承 FixIt 主题的以下配置
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

