#[站点信息]
site_name: Lucifer's Blog
site_url: https://www.ctf-blog.sbs
site_author: JimmyL

#[仓库地址]
repo_url: https://github.com/Lucifer-Jimmy/JimmyL.github.io
repo_name: JimmyL.github.io

#[Copyright/版权声明]
copyright: Copyright &copy; 2024 JimmyL

#[UI]
theme:
  name: material
  #custom_dir: docs/overrides
  language: zh
  font: false
  #[网站角标]
  #favicon: false

  #[右上角图标]
  icon:
    repo: fontawesome/brands/github

  #[404页面]
  static_templates:
    - 404.html

  palette:
    #[顶部颜色]
    #primary: indigo

    #[明暗主题按钮]
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  feature:
    - announce.dismiss
    #- header.autohide  #[自动隐藏顶部]
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest  #[搜索输入一些字母时推荐补全整个单词]
    - search.highlight  #[搜索出的文章关键词高亮]
    - search.share  #[搜索分享按钮]
    - navigation.expand
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.code.annotate

extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en

nav:
  - 主页: index.md
  - WriteUP:
    - CTFHub之HTTP协议: WriteUP/CTFHUB之HTTP协议.md
    - CTFHub之信息泄露: WriteUP/CTFHUB之信息泄露.md
    - CTFHub之密码口令: WriteUP/CTFHUB之密码口令.md
    - 攻防世界之Web新手模式: WriteUP/攻防世界之Web新手模式.md
    - NSSCTF之Web入门: WriteUP/NSSCTF之Web入门.md
    - CTF_show之菜狗杯: WriteUP/CTF_Show之菜狗杯.md
    - CTFhub之SQL注入: WriteUP/CTFHUB之SQL注入.md
    - 2024-BaseCTF-新生赛: WriteUP/BaseCTF_2024_新生赛.md
    - NSSCTF的WriteUP: WriteUP/NSSCTF的WriteUP.md
  - Notes:
    - Java反序列化学习: Notes/Java反序列化学习.md
  - 学习日记: 
    - 2024-08-07: Daily/2024-08-07.md

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  #- callouts
  - md_in_html
  - markdown.extensions.abbr  #[支持Markdown文件上方自定义标题标签等]
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - mdx_truly_sane_lists

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  #[LaTeX支持]
      generic: true
  - toc:
      permalink: true  #[固定标题位置为当前位置]
  - pymdownx.highlight:  #[代码块高亮]
      anchor_linenums: true
      linenums: true  #[显示行号]
      auto_title: true  #[显示编程语言名称]
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js