#[站点信息]
site_name: Lucifer's Blog
site_url: https://www.ctf-blog.sbs
site_author: JimmyL

#[仓库地址]
repo_url: https://github.com/Lucifer-Jimmy/JimmyL.github.io
repo_name: JimmyL.github.io

#[Copyright/版权声明]
copyright: Copyright &copy; 2024 JimmyL

#[UI]
theme:
  name: material
  #custom_dir: docs/overrides
  language: zh
  font: false
  #[网站角标]
  #favicon: false

  #[右上角图标]
  icon:
    repo: fontawesome/brands/github

  #[404页面]
  static_templates:
    - 404.html

  palette:
    #[顶部颜色]
    #primary: indigo

    #[明暗主题按钮]
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式


  feature:
    - announce.dismiss
    - navigation.instant #自动隐藏